### ISSUE TITLE
SSL is not configured for CentOS/RHEL

### ISSUE THREAD

**Issue by cvoltz** [mrlesmithjr/ansible-apache2#16]
While one can specify 443 for `apache2_default_port`, the role doesn't appear to do any SSL/TLS configuration for CentOS/RHEL. In fact, the role doesn't install the `mod_ssl` package. As a result, setting `apache2_default_port` to 443 results in a server one can't access. It appears the other distros are setup with some support for SSL/TLS so this is probably just an oversight of the CentOS/RHEL support.

**Comment by mrlesmithjr** [comment]
@cvoltz - Thank you for raising this issue as well. I'll look into this one too along with #15 when time permits.
